{"name": "Проверка создание курьера, если создать пользователя с логином, который уже есть, возвращается ошибка.", "status": "passed", "start": 1747309433697, "stop": 1747309433783, "uuid": "8ca3a16d-dac0-4511-ba36-3042ddab4ddd", "historyId": "f70abf9b17655f349f69212a0bc547c4", "testCaseId": "f70abf9b17655f349f69212a0bc547c4", "fullName": "test.test_create_courier.TestCreateCourier#test_create_courier_double_login", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "GeoPC"}, {"name": "thread", "value": "17172-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_create_courier"}]}