{"name": "Проверка создание курьера, если создать пользователя с логином, который уже есть, возвращается ошибка.", "status": "passed", "start": 1747845775283, "stop": 1747845775337, "uuid": "bea61190-ff95-4b55-8480-6566175c0796", "historyId": "f70abf9b17655f349f69212a0bc547c4", "testCaseId": "f70abf9b17655f349f69212a0bc547c4", "fullName": "test.test_create_courier.TestCreateCourier#test_create_courier_double_login", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "GeoPC"}, {"name": "thread", "value": "25156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_create_courier"}]}