{"name": "Проверка создание курьера, если создать пользователя с логином, который уже есть, возвращается ошибка.", "status": "passed", "start": 1747302660156, "stop": 1747302660273, "uuid": "fcacfdcd-c4a3-4fe6-ba57-a2fab1a9873e", "historyId": "5ed32161bffc30105485bb86b08b2eb2", "testCaseId": "5ed32161bffc30105485bb86b08b2eb2", "fullName": "test.test_creat_courier.TestCreateCourier#test_create_courier_double_login", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_creat_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "GeoPC"}, {"name": "thread", "value": "10980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_creat_courier"}]}